// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mclwkttfvenlkonifwgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jbHdrdHRmdmVubGtvbmlmd2dkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5ODA0MzksImV4cCI6MjA3MDU1NjQzOX0.zzfMxX9EgmSOfZ3EwSW2q2szxgv4gLlO8kTzpnj7Qdo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});